=== BulkSecurityGeneratorProjectV2/Yuyue__myfaces/src/codegen/org/apache/myfaces/codegen/resource/Component.dtd
<!ELEMENT component
    (component-class, base-class, component-type?, component-family?, renderer-type?, field*)>
<!ATTLIST component
    generateConstructor  (true|false) #IMPLIED
    generateStateMethods (true|false) #IMPLIED
    generateUserRoleMethods (true|false) #IMPLIED>

<!ELEMENT component-class (#PCDATA)>
<!ELEMENT base-class (#PCDATA)>
<!ELEMENT component-type (#PCDATA)>
<!ELEMENT component-family (#PCDATA)>
<!ELEMENT renderer-type (#PCDATA)>

<!ELEMENT field (name, type, default-value?)>
<!ATTLIST field
    proprietary         (true|false) #IMPLIED
    generateProperty    (true|false) #IMPLIED
    generateSetter      (true|false) #IMPLIED
    saveState           (true|false) #IMPLIED>

<!ELEMENT name (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT default-value (#PCDATA)>

=== BulkSecurityGeneratorProjectV2/Yuyue__myfaces/src/components/org/apache/myfaces/component/html/ext/HtmlCommandLink.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE component PUBLIC
  "-//MyFaces//DTD MyFaces component def 1.0//EN"
  "http://myfaces.sourceforge.net/dtd/Component.dtd">
<component generateStateMethods="true" generateUserRoleMethods="true" >
    <component-class>net.sourceforge.myfaces.component.html.ext.HtmlCommandLink</component-class>
    <base-class>javax.faces.component.html.HtmlCommandLink</base-class>
    <component-type>net.sourceforge.myfaces.HtmlCommandLink</component-type>
    <renderer-type>net.sourceforge.myfaces.Link</renderer-type>
    <field>
        <name>target</name>
        <type>java.lang.String</type>
    </field>
    <field>
        <name>enabledOnUserRole</name>
        <type>java.lang.String</type>
    </field>
    <field>
        <name>visibleOnUserRole</name>
        <type>java.lang.String</type>
    </field>
</component>

=== BulkSecurityGeneratorProjectV2/Yuyue__myfaces/src/myfaces/org/apache/myfaces/component/ext/HtmlDataList.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE component PUBLIC
  "-//MyFaces//DTD MyFaces component def 1.0//EN"
  "http://myfaces.sourceforge.net/dtd/Component.dtd">
<component>
    <component-class>net.sourceforge.myfaces.component.ext.HtmlDataList</component-class>
    <base-class>javax.faces.component.UIData</base-class>
    <component-type>net.sourceforge.myfaces.HtmlDataList</component-type>
    <renderer-type>net.sourceforge.myfaces.List</renderer-type>
    <field>
        <name>layout</name>
        <type>java.lang.String</type>
    </field>
    <field>
        <name>firstRowFlag</name>
        <type>java.lang.String</type>
    </field>
    <field>
        <name>lastRowFlag</name>
        <type>java.lang.String</type>
    </field>
</component>

=== BulkSecurityGeneratorProjectV2/Yuyue__myfaces/src/components/org/apache/myfaces/custom/fileupload/HtmlInputFileUpload.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE component PUBLIC
  "-//MyFaces//DTD MyFaces component def 1.0//EN"
  "http://myfaces.sourceforge.net/dtd/Component.dtd">
<component>
    <component-class>net.sourceforge.myfaces.custom.fileupload.HtmlInputFileUpload</component-class>
    <base-class>javax.faces.component.html.HtmlInputText</base-class>
    <component-type>net.sourceforge.myfaces.HtmlInputFileUpload</component-type>
    <component-family>javax.faces.Input</component-family>
    <renderer-type>net.sourceforge.myfaces.FileUpload</renderer-type>
    <field>
        <name>accept</name>
        <type>java.lang.String</type>
    </field>
</component>

=== BulkSecurityGeneratorProjectV2/Yuyue__myfaces/src/components/org/apache/myfaces/custom/datatablescroller/HtmlDataTableScroller.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE component PUBLIC
  "-//MyFaces//DTD MyFaces component def 1.0//EN"
  "http://myfaces.sourceforge.net/dtd/Component.dtd">
<component>
    <component-class>net.sourceforge.myfaces.custom.datatablescroller.HtmlDataTableScroller</component-class>
    <base-class>javax.faces.component.UICommand</base-class>
    <component-type>net.sourceforge.myfaces.HtmlDataTableScroller</component-type>
    <component-family>javax.faces.Command</component-family>
    <renderer-type>net.sourceforge.myfaces.TableScroller</renderer-type>
    <field>
        <name>for</name>
        <type>java.lang.String</type>
    </field>
</component>

=== BulkSecurityGeneratorProjectV2/Yuyue__myfaces/src/myfaces/org/apache/myfaces/component/html/MyFacesHtmlMessages.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE component PUBLIC
  "-//MyFaces//DTD MyFaces component def 1.0//EN"
  "http://myfaces.sourceforge.net/dtd/Component.dtd">
<component>
    <component-class>net.sourceforge.myfaces.component.html.MyFacesHtmlMessages</component-class>
    <base-class>javax.faces.component.html.HtmlMessages</base-class>
    <component-type>net.sourceforge.myfaces.HtmlMessages</component-type>
    <component-family>javax.faces.Messages</component-family>
    <renderer-type>net.sourceforge.myfaces.Messages</renderer-type>
    <field>
        <name>showInputLabel</name>
        <type>boolean</type>
        <default-value>false</default-value>
    </field>
</component>

=== BulkSecurityGeneratorProjectV2/Yuyue__myfaces/src/components/org/apache/myfaces/component/html/ext/HtmlMessage.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE component PUBLIC
  "-//MyFaces//DTD MyFaces component def 1.0//EN"
  "http://myfaces.sourceforge.net/dtd/Component.dtd">
<component>
    <component-class>net.sourceforge.myfaces.component.html.ext.HtmlMessage</component-class>
    <base-class>javax.faces.component.html.HtmlMessage</base-class>
    <component-type>net.sourceforge.myfaces.HtmlMessage</component-type>
    <component-family>javax.faces.Message</component-family>
    <renderer-type>javax.faces.Message</renderer-type>
    <field>
        <name>showColon</name>
        <type>boolean</type>
        <default-value>true</default-value>
    </field>
</component>

=== BulkSecurityGeneratorProjectV2/Yuyue__myfaces/src/components/org/apache/myfaces/custom/tree/Tree.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE component PUBLIC
  "-//MyFaces//DTD MyFaces component def 1.0//EN"
  "http://myfaces.sourceforge.net/dtd/Component.dtd">
<component>
    <component-class>org.apache.myfaces.custom.tree.HtmlTree</component-class>
    <base-class>javax.faces.component.html.HtmlForm</base-class>
    <component-type>org.apache.myfaces.HtmlTree</component-type>
    <component-family>org.apache.myfaces.HtmlTree</component-family>
    <renderer-type>org.apache.myfaces.HtmlTree</renderer-type>
    <field>
        <name>value</name>
        <type>java.lang.String</type>
    </field>
    <field>
        <name>styleClass</name>
        <type>java.lang.String</type>
    </field>
    <field>
        <name>nodeClass</name>
        <type>java.lang.String</type>
    </field>
    <field>
        <name>selectedNodeClass</name>
        <type>java.lang.String</type>
    </field>
    <field>
        <name>iconLine</name>
        <type>java.lang.String</type>
    </field>
    <field>
        <name>iconNoline</name>
        <type>java.lang.String</type>
    </field>
    <field>
        <name>iconChild</name>
        <type>java.lang.String</type>
    </field>
    <field>
        <name>iconChildFirst</name>
        <type>java.lang.String</type>
    </field>
    <field>
        <name>iconChildMiddle</name>
        <type>java.lang.String</type>
    </field>
    <field>
        <name>iconChildLast</name>
        <type>java.lang.String</type>
    </field>
    <field>
        <name>iconNodeOpen</name>
        <type>java.lang.String</type>
    </field>
    <field>
        <name>iconNodeOpenFirst</name>
        <type>java.lang.String</type>
    </field>
    <field>
        <name>iconNodeOpenMiddle</name>
        <type>java.lang.String</type>
    </field>
    <field>
        <name>iconNodeOpenLast</name>
        <type>java.lang.String</type>
    </field>
    <field>
        <name>iconNodeClose</name>
        <type>java.lang.String</type>
    </field>
    <field>
        <name>iconNodeCloseFirst</name>
        <type>java.lang.String</type>
    </field>
    <field>
        <name>iconNodeCloseMiddle</name>
        <type>java.lang.String</type>
    </field>
    <field>
        <name>iconNodeCloseLast</name>
        <type>java.lang.String</type>
    </field>
</component>

=== BulkSecurityGeneratorProjectV2/Yuyue__myfaces/src/components/org/apache/myfaces/custom/navmenu/jscookmenu/HtmlCommandJSCookMenu.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE component PUBLIC
  "-//MyFaces//DTD MyFaces component def 1.0//EN"
  "http://myfaces.sourceforge.net/dtd/Component.dtd">
<component generateUserRoleMethods="true" >
    <component-class>net.sourceforge.myfaces.custom.navmenu.jscookmenu.HtmlCommandJSCookMenu</component-class>
    <base-class>javax.faces.component.UICommand</base-class>
    <component-type>net.sourceforge.myfaces.JSCookMenu</component-type>
    <component-family>javax.faces.Command</component-family>
    <field>
        <name>layout</name>
        <type>java.lang.String</type>
    </field>
    <field>
        <name>theme</name>
        <type>java.lang.String</type>
    </field>
    <field>
        <name>enabledOnUserRole</name>
        <type>java.lang.String</type>
    </field>
    <field>
        <name>visibleOnUserRole</name>
        <type>java.lang.String</type>
    </field>
</component>
