=== BulkSecurityGeneratorProjectV2/Yuyue__myfaces/src/codegen/org/apache/myfaces/codegen/resource/Component.dtd
<!ELEMENT component
    (component-class, base-class, component-type?, component-family?, renderer-type?, field*)>
<!ATTLIST component
    generateConstructor  (true|false) #IMPLIED
    generateStateMethods (true|false) #IMPLIED
    generateUserRoleMethods (true|false) #IMPLIED>

<!ELEMENT component-class (#PCDATA)>
<!ELEMENT base-class (#PCDATA)>
<!ELEMENT component-type (#PCDATA)>
<!ELEMENT component-family (#PCDATA)>
<!ELEMENT renderer-type (#PCDATA)>

<!ELEMENT field (name, type, default-value?)>
<!ATTLIST field
    proprietary         (true|false) #IMPLIED
    generateProperty    (true|false) #IMPLIED
    generateSetter      (true|false) #IMPLIED
    saveState           (true|false) #IMPLIED>

<!ELEMENT name (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT default-value (#PCDATA)>

=== BulkSecurityGeneratorProjectV2/Yuyue__myfaces/src/myfaces/org/apache/myfaces/component/ext/HtmlInputCalendar.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE component PUBLIC
  "-//MyFaces//DTD MyFaces component def 1.0//EN"
  "http://myfaces.sourceforge.net/dtd/Component.dtd">
<component>
    <component-class>net.sourceforge.myfaces.component.ext.HtmlInputCalendar</component-class>
    <base-class>javax.faces.component.UIInput</base-class>
    <component-type>net.sourceforge.myfaces.HtmlInputCalendar</component-type>
    <component-family>javax.faces.Input</component-family>
    <renderer-type>net.sourceforge.myfaces.Calendar</renderer-type>
    <field>
        <name>monthYearRowClass</name>
        <type>java.lang.String</type>
    </field>
    <field>
        <name>weekRowClass</name>
        <type>java.lang.String</type>
    </field>
    <field>
        <name>dayCellClass</name>
        <type>java.lang.String</type>
    </field>
    <field>
        <name>currentDayCellClass</name>
        <type>java.lang.String</type>
    </field>
</component>

=== BulkSecurityGeneratorProjectV2/Yuyue__myfaces/src/components/org/apache/myfaces/component/html/ext/HtmlOutputText.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE component PUBLIC
  "-//MyFaces//DTD MyFaces component def 1.0//EN"
  "http://myfaces.sourceforge.net/dtd/Component.dtd">
<component generateStateMethods="true" generateUserRoleMethods="true" >
    <component-class>net.sourceforge.myfaces.component.html.ext.HtmlOutputText</component-class>
    <base-class>javax.faces.component.html.HtmlOutputText</base-class>
    <component-type>net.sourceforge.myfaces.HtmlOutputText</component-type>
    <field>
        <name>enabledOnUserRole</name>
        <type>java.lang.String</type>
    </field>
    <field>
        <name>visibleOnUserRole</name>
        <type>java.lang.String</type>
    </field>
</component>
