=== BulkSecurityGeneratorProjectV2/Yuyue__myfaces/src/codegen/org/apache/myfaces/codegen/resource/Component.dtd
<!ELEMENT component
    (component-class, base-class, component-type?, component-family?, renderer-type?, field*)>
<!ATTLIST component
    generateConstructor  (true|false) #IMPLIED
    generateStateMethods (true|false) #IMPLIED
    generateUserRoleMethods (true|false) #IMPLIED>

<!ELEMENT component-class (#PCDATA)>
<!ELEMENT base-class (#PCDATA)>
<!ELEMENT component-type (#PCDATA)>
<!ELEMENT component-family (#PCDATA)>
<!ELEMENT renderer-type (#PCDATA)>

<!ELEMENT field (name, type, default-value?)>
<!ATTLIST field
    proprietary         (true|false) #IMPLIED
    generateProperty    (true|false) #IMPLIED
    generateSetter      (true|false) #IMPLIED
    saveState           (true|false) #IMPLIED>

<!ELEMENT name (#PCDATA)>
<!ELEMENT type (#PCDATA)>
<!ELEMENT default-value (#PCDATA)>

=== BulkSecurityGeneratorProjectV2/Yuyue__myfaces/src/components/org/apache/myfaces/component/html/ext/HtmlDataTable.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE component PUBLIC
  "-//MyFaces//DTD MyFaces component def 1.0//EN"
  "http://myfaces.sourceforge.net/dtd/Component.dtd">
<component generateStateMethods="false" >
    <component-class>net.sourceforge.myfaces.component.html.ext.HtmlDataTable</component-class>
    <base-class>javax.faces.component.html.HtmlDataTable</base-class>
    <component-type>net.sourceforge.myfaces.HtmlDataTable</component-type>
    <field>
        <name>preserveDataModel</name>
        <type>boolean</type>
        <default-value>false</default-value>
    </field>
    <field>
        <name>preserveSort</name>
        <type>boolean</type>
        <default-value>false</default-value>
    </field>
    <field>
        <name>enabledOnUserRole</name>
        <type>java.lang.String</type>
    </field>
    <field>
        <name>visibleOnUserRole</name>
        <type>java.lang.String</type>
    </field>
    <field>
        <name>renderedIfEmpty</name>
        <type>boolean</type>
        <default-value>true</default-value>
    </field>
</component>

=== BulkSecurityGeneratorProjectV2/Yuyue__myfaces/src/components/org/apache/myfaces/custom/layout/HtmlPanelLayout.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE component PUBLIC
  "-//MyFaces//DTD MyFaces component def 1.0//EN"
  "http://myfaces.sourceforge.net/dtd/Component.dtd">
<component>
    <component-class>net.sourceforge.myfaces.custom.layout.HtmlPanelLayout</component-class>
    <base-class>javax.faces.component.html.HtmlPanelGroup</base-class>
    <component-type>net.sourceforge.myfaces.HtmlPanelLayout</component-type>
    <component-family>javax.faces.Panel</component-family>
    <renderer-type>net.sourceforge.myfaces.Layout</renderer-type>
    <field>
        <name>layout</name>
        <type>java.lang.String</type>
    </field>
    <field>
        <name>headerClass</name>
        <type>java.lang.String</type>
    </field>
    <field>
        <name>navigationClass</name>
        <type>java.lang.String</type>
    </field>
    <field>
        <name>bodyClass</name>
        <type>java.lang.String</type>
    </field>
    <field>
        <name>footerClass</name>
        <type>java.lang.String</type>
    </field>
    <field>
        <name>headerStyle</name>
        <type>java.lang.String</type>
    </field>
    <field>
        <name>navigationStyle</name>
        <type>java.lang.String</type>
    </field>
    <field>
        <name>bodyStyle</name>
        <type>java.lang.String</type>
    </field>
    <field>
        <name>footerStyle</name>
        <type>java.lang.String</type>
    </field>
</component>

=== BulkSecurityGeneratorProjectV2/Yuyue__myfaces/src/components/org/apache/myfaces/custom/datascroller/HtmlDataScroller.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE component PUBLIC
  "-//MyFaces//DTD MyFaces component def 1.0//EN"
  "http://myfaces.sourceforge.net/dtd/Component.dtd">
<component>
    <component-class>net.sourceforge.myfaces.custom.datascroller.HtmlDataScroller</component-class>
    <base-class>javax.faces.component.UIComponentBase</base-class>
    <component-type>net.sourceforge.myfaces.HtmlDataScroller</component-type>
    <component-family>javax.faces.Panel</component-family>
    <renderer-type>net.sourceforge.myfaces.DataScroller</renderer-type>
    <field>
        <name>for</name>
        <type>java.lang.String</type>
    </field>
</component>

=== BulkSecurityGeneratorProjectV2/Yuyue__myfaces/src/components/org/apache/myfaces/custom/checkbox/HtmlCheckbox.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE component PUBLIC
  "-//MyFaces//DTD MyFaces component def 1.0//EN"
  "http://myfaces.sourceforge.net/dtd/Component.dtd">
<component>
    <component-class>net.sourceforge.myfaces.custom.checkbox.HtmlCheckbox</component-class>
    <base-class>javax.faces.component.UIComponentBase</base-class>
    <component-type>net.sourceforge.myfaces.HtmlCheckbox</component-type>
    <component-family>net.sourceforge.myfaces.Checkbox</component-family>
    <renderer-type>net.sourceforge.myfaces.Checkbox</renderer-type>
    <field>
        <name>for</name>
        <type>java.lang.String</type>
    </field>
    <field>
        <name>index</name>
        <type>int</type>
    </field>
</component>

=== BulkSecurityGeneratorProjectV2/Yuyue__myfaces/src/components/org/apache/myfaces/component/html/ext/HtmlMessages.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE component PUBLIC
  "-//MyFaces//DTD MyFaces component def 1.0//EN"
  "http://myfaces.sourceforge.net/dtd/Component.dtd">
<component generateUserRoleMethods="true" >
    <component-class>net.sourceforge.myfaces.component.html.ext.HtmlMessages</component-class>
    <base-class>javax.faces.component.html.HtmlMessages</base-class>
    <component-type>net.sourceforge.myfaces.HtmlMessages</component-type>
    <renderer-type>net.sourceforge.myfaces.Messages</renderer-type>
    <field>
        <name>summaryFormat</name>
        <type>java.lang.String</type>
    </field>
    <field>
        <name>globalSummaryFormat</name>
        <type>java.lang.String</type>
    </field>
    <field>
        <name>detailFormat</name>
        <type>java.lang.String</type>
    </field>
    <field>
        <name>enabledOnUserRole</name>
        <type>java.lang.String</type>
    </field>
    <field>
        <name>visibleOnUserRole</name>
        <type>java.lang.String</type>
    </field>
</component>

=== BulkSecurityGeneratorProjectV2/Yuyue__myfaces/src/components/org/apache/myfaces/custom/radio/HtmlRadio.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE component PUBLIC
  "-//MyFaces//DTD MyFaces component def 1.0//EN"
  "http://myfaces.sourceforge.net/dtd/Component.dtd">
<component>
    <component-class>net.sourceforge.myfaces.custom.radio.HtmlRadio</component-class>
    <base-class>javax.faces.component.UIComponentBase</base-class>
    <component-type>net.sourceforge.myfaces.HtmlRadio</component-type>
    <component-family>net.sourceforge.myfaces.Radio</component-family>
    <field>
        <name>for</name>
        <type>java.lang.String</type>
    </field>
    <field>
        <name>index</name>
        <type>int</type>
        <default-value>-1</default-value>
    </field>
</component>

=== BulkSecurityGeneratorProjectV2/Yuyue__myfaces/src/components/org/apache/myfaces/component/html/ext/HtmlPanelGroup.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE component PUBLIC
  "-//MyFaces//DTD MyFaces component def 1.0//EN"
  "http://myfaces.sourceforge.net/dtd/Component.dtd">
<component generateUserRoleMethods="true" >
    <component-class>net.sourceforge.myfaces.component.html.ext.HtmlPanelGroup</component-class>
    <base-class>javax.faces.component.html.HtmlPanelGroup</base-class>
    <component-type>net.sourceforge.myfaces.HtmlPanelGroup</component-type>
    <component-family>javax.faces.Panel</component-family>
    <renderer-type>javax.faces.Group</renderer-type>
    <field>
        <name>enabledOnUserRole</name>
        <type>java.lang.String</type>
    </field>
    <field>
        <name>visibleOnUserRole</name>
        <type>java.lang.String</type>
    </field>
</component>

=== BulkSecurityGeneratorProjectV2/Yuyue__myfaces/src/myfaces/org/apache/myfaces/component/html/MyFacesHtmlCommandLink.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE component PUBLIC
  "-//MyFaces//DTD MyFaces component def 1.0//EN"
  "http://myfaces.sourceforge.net/dtd/Component.dtd">
<component generateStateMethods="true">
    <component-class>net.sourceforge.myfaces.component.html.MyFacesHtmlCommandLink</component-class>
    <base-class>javax.faces.component.html.HtmlCommandLink</base-class>
    <component-type>net.sourceforge.myfaces.HtmlCommandLink</component-type>
    <component-family>javax.faces.Command</component-family>
    <renderer-type>net.sourceforge.myfaces.Link</renderer-type>
    <field>
        <name>target</name>
        <type>java.lang.String</type>
    </field>
    <field generateProperty="false" >
        <name>actionUpdateProperty</name>
        <type>javax.faces.el.ValueBinding</type>
    </field>
    <field>
        <name>actionUpdateValue</name>
        <type>java.lang.String</type>
    </field>
</component>
